"""
TOOL-ANGEL Bootstrap Generator
Version: 0.1.0
"""

from pathlib import Path

DIRECTORIES = [
    "docs",
    "specs",
    "kernel",
    "sdk",
    "runtime",
    "brain",
    "memory",
    "agents",
    "tests",
]

def create_structure():
    for directory in DIRECTORIES:
        Path(directory).mkdir(parents=True, exist_ok=True)
        readme = Path(directory) / "README.md"
        if not readme.exists():
            readme.write_text(
                f"# {directory.capitalize()}\n\n"
                f"Generated by TOOL-ANGEL Bootstrap Generator.\n",
                encoding="utf-8",
            )

if __name__ == "__main__":
    create_structure()
    print("Bootstrap completed successfully.")
